### ISSUE TITLE
Simplify logic in PresenterBundle

### ISSUE THREAD

**Issue by dalewking** [grandstaish/hello-mvp-dagger-2#1]
You have code like this for all the different types in PresenterBundle:

        Object o = map.get(key);
        if (o == null) {
            return defaultValue;
        }
        try {
            return (Boolean) o;
        } catch (ClassCastException e) {
            return defaultValue;
        }

Would be much better to do the following which is simpler and never has to deal with catching exceptions:

        Object o = map.get(key);
        if (o instanceOf Boolean) {
            return (Boolean) o;
        }
        else {
            return defaultValue;
        }

Or if you want to go for terse:

        Object o = map.get(key);
        return o instanceOf Boolean? (Boolean) o : defaultValue;

**Comment by grandstaish** [comment]
That's true, I just copied the actual Bundle class from the Android framework https://github.com/android/platform_frameworks_base/blob/master/core/java/android/os/Bundle.java. I'm not sure why they have written it in this way. 

Either way, after the episode of Fragmented podcast with Jake Wharton, I have followed his advice and have started using the Framework's Bundle code and use Robolectric for unit testing instead of using this class essentially making this class deprecated.

**Comment by dalewking** [comment]
I think using the framework's bundle code is a bad idea as it ties your
presenters to the Android framework. Presenters should be able to be 100 %
pure java code and actually be reusable outside of Android

**Comment by grandstaish** [comment]
I used to think that too but I disagree now after writing an app using that approach. The reason I disagree is because too much "business logic" ends up outside of the presenters because it contains Android Framework references. Examples include logic with Intents, Bundles, Matrices, and so on. All of this stuff can easily be unit tested. However if your code is intended to be used outside of Android (mine isn't), then yes, that's a separate problem you'll have to solve.
